[package]
name = "rendown"
version = "0.0.1"
license = "MIT"
description = "Streaming CommonMark/markdown renderer for terminal (ANSI)."
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = true

[lib]
name = "rendown"
path = "src/lib.rs"

[dependencies]
anstyle.workspace = true
anstyle-syntect.workspace = true
crossterm = { workspace = true, default-features = false }
html-escape.workspace = true
linkify.workspace = true
pulldown-cmark.workspace = true
supports-color.workspace = true
syntect.workspace = true
two-face = { workspace = true, default-features = false, features = ["syntect-fancy"] }
unicode-linebreak.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
url.workspace = true

[lints.rust]
linker_messages = "allow"
