//! Shared state handles bundle threaded through the extracted MainShell blocks.

use super::*;

/// Bundle of shell state handles threaded through the extracted MainShell blocks:
/// the async tick loop, the terminal key handler, and the render phase.
#[derive(Clone)]
pub(crate) struct ShellCtx {
    pub(crate) active_plan_file: Ref<Option<String>>,
    pub(crate) activity_label: State<String>,
    pub(crate) activity_started_at: Ref<Option<Instant>>,
    pub(crate) agent_mode: State<AgentMode>,
    pub(crate) agent_session: Option<Arc<CodingAgentSession>>,
    pub(crate) agent_session_slot: Ref<Option<Arc<CodingAgentSession>>>,
    pub(crate) agent_turn_active: State<bool>,
    pub(crate) allow_mode_change_while_busy: State<bool>,
    pub(crate) approval_selected: State<usize>,
    pub(crate) auto_expand_thinking: bool,
    pub(crate) bootstrap_config: Ref<Option<TuiBootstrapConfig>>,
    pub(crate) bootstrap_phase: Ref<BootstrapPhase>,
    pub(crate) bootstrap_rx: Ref<Option<UnboundedReceiver<BootstrapUiEvent>>>,
    pub(crate) bootstrap_worker_started: Ref<bool>,
    pub(crate) busy: State<bool>,
    pub(crate) busy_started_at: Ref<Option<Instant>>,
    pub(crate) chrome_eager_paint_done: Ref<bool>,
    pub(crate) chrome_full_redraw_pending: Ref<bool>,
    pub(crate) chrome_refresh_pending: State<bool>,
    pub(crate) chrome_stats: State<ChromeStats>,
    pub(crate) chrome_tick: Ref<u32>,
    pub(crate) chrome_ui_revision: State<u64>,
    pub(crate) clipboard_toast: State<Option<elph_tui::ClipboardNotice>>,
    pub(crate) image_attachments: Ref<Vec<elph_tui::ImageAttachment>>,
    pub(crate) colored_status_footer: bool,
    pub(crate) density: crate::tui::transcript::LogDensity,
    pub(crate) confetti_frame: State<u32>,
    pub(crate) confetti_runtime: Ref<Option<ConfettiRuntime>>,
    pub(crate) cwd: PathBuf,
    pub(crate) cwd_for_loop: PathBuf,
    pub(crate) cwd_for_mention_index: PathBuf,
    pub(crate) draft: State<String>,
    pub(crate) ephemeral_banner: State<Option<EphemeralBanner>>,
    pub(crate) ephemeral_banner_generation: Ref<EphemeralBannerGeneration>,
    pub(crate) ephemeral_expire: Ref<EphemeralExpireChannel>,
    pub(crate) event_applier: Ref<TranscriptEventApplier>,
    pub(crate) execution_env: Arc<LocalExecutionEnv>,
    pub(crate) hook_host: HookHost,
    pub(crate) hook_host_for_loop: HookHost,
    pub(crate) fallback_context_limit: u64,
    pub(crate) fallback_model_label: String,
    pub(crate) fallback_model_label_for_chrome: String,
    pub(crate) fallback_supports_images: bool,
    pub(crate) atomic_paste: bool,
    pub(crate) file_picker_active: Ref<bool>,
    pub(crate) file_picker_index: State<usize>,
    pub(crate) file_picker_key_handled: Ref<bool>,
    pub(crate) file_picker_query: Ref<String>,
    pub(crate) file_picker_show_hidden: State<bool>,
    pub(crate) file_picker_suppressed: Ref<bool>,
    pub(crate) footer_token_display: String,
    pub(crate) force_editor_clear: Ref<bool>,
    pub(crate) force_palette_sync: Ref<bool>,
    pub(crate) git_footer: State<Option<GitFooterInfo>>,
    pub(crate) idle_status_notice: Ref<Option<IdleStatusNotice>>,
    pub(crate) input_prefix_kind: Ref<InputPrefixKind>,
    pub(crate) last_activity_label: Ref<String>,
    pub(crate) last_arrow_up_at: Ref<Instant>,
    pub(crate) last_event_burst: Ref<usize>,
    pub(crate) last_transcript_publish: Ref<Instant>,
    pub(crate) layout_screen_size_for_loop: State<(u16, u16)>,
    pub(crate) live_cursor: Ref<usize>,
    pub(crate) live_draft: Ref<String>,
    pub(crate) live_session_id: State<String>,
    pub(crate) mention_index: Ref<Option<Arc<MentionSearchIndex>>>,
    pub(crate) mention_index_requested: Ref<bool>,
    pub(crate) messages: State<Vec<TranscriptMessage>>,
    pub(crate) messages_arc: Ref<Arc<RwLock<Vec<TranscriptMessage>>>>,
    pub(crate) messages_arc_inner: Arc<RwLock<Vec<TranscriptMessage>>>,
    pub(crate) messages_for_tick: State<Vec<TranscriptMessage>>,
    pub(crate) messages_revision: State<u64>,
    pub(crate) messages_revision_for_tick: State<u64>,
    pub(crate) model_filter: State<String>,
    pub(crate) model_input_focus: State<ModelSelectorFocus>,
    pub(crate) model_provider_index: State<usize>,
    pub(crate) model_selected_index: State<usize>,
    pub(crate) new_session_requested: Ref<bool>,
    /// When set, next tick reloads bootstrap with this session id (`/resume <id>`).
    pub(crate) resume_session_requested: Ref<Option<String>>,
    pub(crate) on_queue_action_click: Handler<(usize, PromptQueueAction)>,
    pub(crate) palette_refresh_pending: State<bool>,
    pub(crate) paths: State<Paths>,
    pub(crate) pending_confetti: Ref<Option<PendingConfetti>>,
    pub(crate) pending_feedback: Ref<bool>,
    pub(crate) pending_memory_flush: Ref<Option<crate::tui::tool_approval::PendingMemoryFlush>>,
    pub(crate) pending_mode_change: Ref<Option<PendingModeChange>>,
    pub(crate) pending_model_selector: Ref<Option<PendingModelSelector>>,
    pub(crate) pending_plan_confirmation: Ref<Option<PendingPlanConfirmation>>,
    pub(crate) pending_retry_prompt: Ref<Option<String>>,
    pub(crate) pending_mcp_auth: Ref<Option<PendingMcpAuthDialog>>,
    pub(crate) pending_mcp_auth_for_tick: Ref<Option<PendingMcpAuthDialog>>,
    pub(crate) pending_mcp_add: Ref<Option<crate::tui::mcp_auth_dialog::PendingMcpAddDialog>>,
    pub(crate) mcp_add_input: State<String>,
    pub(crate) mcp_add_field: State<crate::tui::mcp_auth_dialog::McpAddField>,
    pub(crate) pending_provider_api_key: Ref<Option<PendingProviderApiKeyDialog>>,
    pub(crate) pending_provider_connect: Ref<Option<PendingProviderConnectDialog>>,
    pub(crate) pending_provider_connect_for_tick: Ref<Option<PendingProviderConnectDialog>>,
    pub(crate) pending_provider_disconnect: Ref<Option<PendingProviderDisconnectDialog>>,
    pub(crate) pending_provider_disconnect_for_tick: Ref<Option<PendingProviderDisconnectDialog>>,
    pub(crate) pending_queue_click: State<Option<(usize, PromptQueueAction)>>,
    pub(crate) pending_quit_confirm: Ref<bool>,
    pub(crate) pending_rename: Ref<Option<PendingRenameDialog>>,
    pub(crate) pending_item_selector: Ref<Option<crate::tui::item_selector::PendingItemSelector>>,
    pub(crate) item_selector_selected: State<usize>,
    pub(crate) pending_thinking_selector: Ref<Option<crate::tui::thinking_selector::PendingThinkingSelector>>,
    pub(crate) thinking_selector_selected: State<usize>,
    pub(crate) pending_scoped_models: Ref<Option<PendingScopedModels>>,
    pub(crate) pending_subagent_output: Ref<Option<PendingSubagentOutputDialog>>,
    pub(crate) pending_system_prompt: Ref<Option<PendingSystemPromptDialog>>,
    /// Inline `/aside` panel above the status row (Grok `/btw` parity).
    pub(crate) pending_aside: Ref<Option<crate::tui::aside_panel::AsidePanelState>>,
    /// Bumped while aside is Loading so the spinner re-renders.
    pub(crate) aside_tick: State<u64>,
    /// Worker chat overlay state (None = closed). All keys live here; the picker
    /// selection highlights via `worker_chat_selected`.
    pub(crate) pending_worker_chat: Ref<Option<crate::tui::worker_chat::WorkerChatState>>,
    /// Picker highlight for the worker chat overlay.
    pub(crate) worker_chat_selected: State<usize>,
    /// Pending inbound worker messages not yet seen (overlay closed). Drives the
    /// footer `⬡` badge color: >0 → yellow. Reset when the overlay opens.
    pub(crate) worker_pending_count: State<usize>,
    pub(crate) pending_tool_approval: Ref<Option<PendingToolApproval>>,
    pub(crate) pending_transcript_notice_expires: Ref<HashMap<&'static str, Instant>>,
    pub(crate) pending_user_question: Ref<Option<PendingUserQuestion>>,
    pub(crate) pre_echoed_user_prompts: State<u32>,
    pub(crate) prompt_editor_mirror: Ref<(String, usize)>,
    pub(crate) atomic_pastes: Ref<Vec<elph_tui::AtomicPaste>>,
    pub(crate) prompt_history: Ref<Vec<String>>,
    pub(crate) prompt_history_index: State<usize>,
    pub(crate) prompt_history_open: State<bool>,
    pub(crate) prompt_queue: Ref<PromptQueue>,
    pub(crate) prompt_templates: State<Vec<PromptTemplate>>,
    pub(crate) provider_connect_api_key: State<String>,
    pub(crate) provider_connect_api_key_for_tick: State<String>,
    pub(crate) provider_connect_filter: State<String>,
    pub(crate) provider_connect_input_focus: State<ProviderConnectFocus>,
    pub(crate) provider_connect_input_focus_for_tick: State<ProviderConnectFocus>,
    pub(crate) provider_connect_selected: State<usize>,
    pub(crate) provider_disconnect_selected: State<usize>,
    pub(crate) question_answer: State<String>,
    pub(crate) question_confirm_focus: State<ConfirmButtonFocus>,
    pub(crate) question_input_focus: State<QuestionInputFocus>,
    pub(crate) question_multi_checked: State<Vec<bool>>,
    pub(crate) question_selected: State<usize>,
    pub(crate) question_validation_error: State<Option<String>>,
    pub(crate) queue_manager_action: State<PromptQueueAction>,
    pub(crate) queue_manager_open: State<bool>,
    pub(crate) queue_manager_selected: State<usize>,
    pub(crate) queue_ui_revision: State<u64>,
    pub(crate) rename_value: State<String>,
    pub(crate) scoped_filter: State<String>,
    pub(crate) scoped_selected_index: State<usize>,
    pub(crate) screen_height: u16,
    pub(crate) screen_width: u16,
    pub(crate) select_mode: State<bool>,
    pub(crate) session_elapsed_secs: State<f64>,
    pub(crate) session_id: String,
    pub(crate) session_scoped_items: Ref<Vec<String>>,
    pub(crate) session_wall_started_at: Ref<Instant>,
    pub(crate) shell_focus: State<ShellFocus>,
    pub(crate) shell_focus_for_tick: State<ShellFocus>,
    pub(crate) shift_held: State<bool>,
    pub(crate) shift_last_pressed: Ref<Option<Instant>>,
    pub(crate) should_exit: State<bool>,
    pub(crate) show_thinking: bool,
    pub(crate) skills: State<Vec<Skill>>,
    pub(crate) skills_count: State<usize>,
    pub(crate) slash_commands: State<Vec<SlashCommand>>,
    pub(crate) slash_palette_active: Ref<bool>,
    pub(crate) slash_palette_index: State<usize>,
    pub(crate) slash_palette_query: Ref<String>,
    pub(crate) styled_content: Ref<String>,
    pub(crate) subagent_output_buffers: Arc<RwLock<HashMap<String, SubagentBuf>>>,
    pub(crate) subagent_output_buffers_state: Ref<Arc<RwLock<HashMap<String, SubagentBuf>>>>,
    pub(crate) subagent_output_scroll: Ref<ScrollViewHandle>,
    pub(crate) subagent_output_scroll_tick: State<u32>,
    pub(crate) suppress_enter_newline: Ref<bool>,
    pub(crate) system_prompt_scroll: Ref<ScrollViewHandle>,
    pub(crate) system_prompt_scroll_tick: Ref<u32>,
    pub(crate) thinking_level: State<ThinkingLevel>,
    pub(crate) transcript_pending: Ref<bool>,
    pub(crate) turn_cancel_requested: Ref<bool>,
    pub(crate) turn_token_tracker: Ref<Option<TurnTokenTracker>>,
    pub(crate) last_turn_stats: Ref<Option<TurnCompleteStats>>,
    /// `ui.turnStats` — show the dimmed per-turn stats card after each completed turn.
    pub(crate) turn_stats_enabled: bool,
    pub(crate) pending_approval_label: Ref<bool>,
    pub(crate) ui_events_slot: Ref<Option<Arc<Mutex<UnboundedReceiver<AgentUiEvent>>>>>,
    pub(crate) user_shell_abort: Ref<Option<CancellationToken>>,
    pub(crate) user_shell_channel: Ref<UserShellChannel>,
    /// Current session todo list (for structured work tracking).
    pub(crate) todos: State<Vec<elph_agent::todos::TodoItem>>,
}
