//! Compress the builtin provider catalogs into per-provider zstd frames.
//!
//! `models/*.json` is the single source of truth (regenerated by `generate-models chat`).
//! Embedding the raw JSON with `include_str!` costs ~1.9 MB of binary per copy, so the
//! frames are built here instead and decompressed lazily at runtime
//! (see `src/models/embedded.rs`). The output stays a single self-contained binary.

use std::env;
use std::fs;
use std::path::PathBuf;

/// zstd level: catalogs compress ~20x and the whole set takes <1s at max level.
const ZSTD_LEVEL: i32 = 19;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let models_dir = manifest_dir.join("models");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let frames_dir = out_dir.join("catalogs");
    fs::create_dir_all(&frames_dir).expect("create catalog frame directory");

    println!("cargo::rerun-if-changed=build.rs");

    let mut catalogs: Vec<(String, String, usize)> = Vec::new();
    let entries = fs::read_dir(&models_dir).expect("read models directory");
    for entry in entries {
        let path = entry.expect("read models directory entry").path();
        if !path.is_file() || path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        // Generator bookkeeping, not a provider catalog.
        if stem == "index" {
            continue;
        }
        println!("cargo::rerun-if-changed=models/{stem}.json");

        let raw = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let frame =
            zstd::bulk::compress(&raw, ZSTD_LEVEL).unwrap_or_else(|e| panic!("compress {}: {e}", path.display()));
        let frame_path = frames_dir.join(format!("{stem}.zst"));
        fs::write(&frame_path, &frame).unwrap_or_else(|e| panic!("write {}: {e}", frame_path.display()));

        catalogs.push((stem.replace('_', "-"), escape_path(&frame_path), raw.len()));
    }
    catalogs.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::from("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("pub(crate) static EMBEDDED_CATALOGS: &[EmbeddedCatalog] = &[\n");
    for (provider_id, frame_path, raw_len) in &catalogs {
        generated.push_str(&format!(
            "    EmbeddedCatalog {{ id: \"{provider_id}\", raw_len: {raw_len}, frame: include_bytes!(\"{frame_path}\") }},\n"
        ));
    }
    generated.push_str("];\n\n");
    generated.push_str("pub(crate) static EMBEDDED_CATALOG_IDS: &[&str] = &[\n");
    for (provider_id, _, _) in &catalogs {
        generated.push_str(&format!("    \"{provider_id}\",\n"));
    }
    generated.push_str("];\n");

    let generated_path = out_dir.join("embedded_catalogs.rs");
    fs::write(&generated_path, generated).unwrap_or_else(|e| panic!("write {}: {e}", generated_path.display()));
}

/// Absolute path literal for `include_bytes!` (Windows separators need escaping).
fn escape_path(path: &std::path::Path) -> String {
    path.to_string_lossy().replace('\\', "\\\\")
}
