# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Elph

on:
  push:
    tags: ["elph-v*.*.*"]

permissions:
  contents: write

concurrency:
  group: release-elph-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/_release-app.yml
    with:
      app: elph
